import type { SupabaseClient } from "@supabase/supabase-js";
import {
  getServiceBySlug,
  getServicePriceCents,
  servicePricingUnit,
  validateSessionCount,
  clampSessionCount,
  isStayOnlyService,
  type ServiceDefinition,
} from "@/lib/services-catalog";
import { assertCoachesAvailable } from "@/lib/coach-availability";
import { formatBookingDates } from "@/lib/schedule-utils";
import {
  bookingExtrasTotalCents,
  bookingGroupHeadcount,
  extrasFromBookingRecord,
  formatBookingExtrasSummary,
  resolveSessionDurationDays,
} from "@/lib/booking-extras";

export type BookingLineItemInput = {
  serviceSlug: string;
  participantNames?: string[];
  quantity?: number;
  sessions?: number;
  participants?: number;
  durationDays: 1 | 2;
};

export type ResolvedBookingItem = {
  serviceSlug: string;
  participantNames: string[];
  quantity: number;
  participants: number;
  durationDays: 1 | 2;
  unitPriceCents: number;
  startDate: string;
  lineTotalCents: number;
};

import { addDays } from "@/lib/dates";

export { addDays } from "@/lib/dates";

export function datesForItem(startDate: string, durationDays: 1 | 2): string[] {
  if (durationDays === 1) return [startDate];
  return [startDate, addDays(startDate, 1)];
}

export function allowedDurations(service: ServiceDefinition): (1 | 2)[] {
  return service.allowedDurations ?? [1];
}

export function normalizeParticipantNames(names: string[]): string[] {
  return names.map((n) => n.trim()).filter(Boolean);
}

export function lineItemTotal(unitPriceCents: number, quantity: number): number {
  return unitPriceCents * quantity;
}

export function sessionLineTotalCents(
  unitPriceCents: number,
  sessions: number,
  participants: number
): number {
  return unitPriceCents * sessions * participants;
}

export function bookingItemLineTotalCents(item: {
  service_slug: string;
  quantity: number;
  unit_price_cents: number;
  participant_names?: string[] | null;
}): number {
  const service = getServiceBySlug(item.service_slug);
  if (service && servicePricingUnit(service) === "session") {
    const participants = Math.max(1, item.participant_names?.length ?? 1);
    return sessionLineTotalCents(item.unit_price_cents, item.quantity, participants);
  }

  return lineItemTotal(item.unit_price_cents, item.quantity);
}

export function bookingItemsTotal(items: ResolvedBookingItem[]): number {
  return items.reduce((sum, item) => sum + item.lineTotalCents, 0);
}

export function formatItemLabel(item: {
  serviceSlug: string;
  durationDays: number;
  participantNames?: string[];
  quantity?: number;
  participants?: number;
  sessions?: number;
}): string {
  const service = getServiceBySlug(item.serviceSlug);
  const title = service?.title ?? item.serviceSlug;
  const names = normalizeParticipantNames(item.participantNames ?? []);
  const pricingUnit = service ? servicePricingUnit(service) : "person";
  const sessions =
    pricingUnit === "session"
      ? Math.max(1, item.sessions ?? item.quantity ?? 1)
      : 1;
  const participants =
    pricingUnit === "session"
      ? Math.max(1, item.participants ?? names.length ?? 1)
      : Math.max(1, item.participants ?? item.quantity ?? names.length ?? 1);
  const autoGeneratedNames =
    names.length > 0 &&
    names.every((name) => /^Participant \d+$/.test(name));

  if (names.length === 0 || autoGeneratedNames) {
    const durationNote = item.durationDays === 2 ? "2 days" : "1 day";
    if (service && isStayOnlyService(service)) {
      return `${title} · ${participants} ${participants === 1 ? "person" : "people"} · ${durationNote} · stay only`;
    }
    if (pricingUnit === "session") {
      return `${title} · ${sessions} ${sessions === 1 ? "session" : "sessions"} · ${participants} ${participants === 1 ? "person" : "people"} · ${durationNote}`;
    }
    return `${title} · ${participants} ${participants === 1 ? "person" : "people"} · ${durationNote}`;
  }

  const days = item.durationDays === 2 ? "2 days" : "1 day";
  if (names.length === 0) {
    return `${title} (${days})`;
  }

  return `${title} (${days}): ${names.join(", ")}`;
}

export function formatItemsSummary(
  items: {
    serviceSlug: string;
    participantNames?: string[];
    quantity?: number;
    durationDays: number;
    startDate: string;
  }[]
): string {
  return items.map((item) => formatItemLabel(item)).join(" · ");
}

export async function resolveBookingItems(
  supabase: SupabaseClient,
  startDate: string,
  items: BookingLineItemInput[]
): Promise<{ items: ResolvedBookingItem[] } | { error: string }> {
  if (!items.length) {
    return { error: "Add at least one activity or accompanying guest" };
  }

  const serviceSlugs = items.map((item) => item.serviceSlug);
  if (new Set(serviceSlugs).size !== serviceSlugs.length) {
    return {
      error:
        "Each course can only be added once per booking. Increase the count instead.",
    };
  }

  const resolved: ResolvedBookingItem[] = [];

  for (const item of items) {
    const service = getServiceBySlug(item.serviceSlug);
    if (!service) {
      return { error: `Unknown service: ${item.serviceSlug}` };
    }

    const pricingUnit = servicePricingUnit(service);
    const stayOnly = isStayOnlyService(service);
    const sessions =
      stayOnly || pricingUnit !== "session"
        ? 1
        : clampSessionCount(service, item.sessions ?? item.quantity ?? 1);
    const participants =
      pricingUnit === "session" && !stayOnly
        ? Math.max(1, Math.floor(item.participants ?? 1))
        : Math.max(1, Math.floor(item.participants ?? item.quantity ?? 1));

    if (!stayOnly) {
      const sessionLimitError = validateSessionCount(service, sessions);
      if (sessionLimitError) {
        return { error: sessionLimitError };
      }
    }

    if (stayOnly) {
      if (participants < 1) {
        return { error: `Add at least one accompanying guest for ${service.title}` };
      }
    } else if (sessions < 1 || participants < 1) {
      return {
        error:
          pricingUnit === "session"
            ? `Set at least one session and one participant for ${service.title}`
            : `Add at least one participant for ${service.title}`,
      };
    }

    const billingQuantity = stayOnly ? participants : pricingUnit === "session" ? sessions : participants;

    const participantNames =
      item.participantNames && normalizeParticipantNames(item.participantNames).length > 0
        ? normalizeParticipantNames(item.participantNames)
        : Array.from({ length: participants }, (_, index) => `Participant ${index + 1}`);

    const qty = billingQuantity;
    const durationDays = item.durationDays === 2 ? 2 : 1;
    const allowed = allowedDurations(service);
    if (!allowed.includes(durationDays)) {
      return {
        error: `${service.title} can only be booked for ${allowed.join(" or ")} day(s)`,
      };
    }

    const neededDates = datesForItem(startDate, durationDays);
    if (!stayOnly) {
      const coachError = await assertCoachesAvailable(supabase, neededDates);
      if (coachError) {
        return { error: coachError };
      }
    }

    const unitPrice = stayOnly ? 0 : getServicePriceCents(service, durationDays);
    const lineTotalCents = stayOnly
      ? 0
      : pricingUnit === "session"
        ? sessionLineTotalCents(unitPrice, sessions, participants)
        : lineItemTotal(unitPrice, participants);

    resolved.push({
      serviceSlug: item.serviceSlug,
      participantNames,
      quantity: qty,
      participants,
      durationDays,
      unitPriceCents: unitPrice,
      startDate,
      lineTotalCents,
    });
  }

  return { items: resolved };
}

export async function reserveBookingSlots(
  supabase: SupabaseClient,
  bookingId: string,
  resolvedItems: ResolvedBookingItem[]
) {
  for (const item of resolvedItems) {
    const { data: bookingItem, error: itemError } = await supabase
      .from("booking_items")
      .insert({
        booking_id: bookingId,
        service_slug: item.serviceSlug,
        quantity: item.quantity,
        participant_names: item.participantNames,
        duration_days: item.durationDays,
        unit_price_cents: item.unitPriceCents,
        start_date: item.startDate,
      })
      .select()
      .single();

    if (itemError || !bookingItem) {
      throw new Error(itemError?.message ?? "Failed to save booking item");
    }
  }
}

export async function releaseBookingSlots(
  supabase: SupabaseClient,
  bookingId: string
) {
  const legacy = await supabase
    .from("bookings")
    .select("session_slot_id, headcount")
    .eq("id", bookingId)
    .single();

  if (!legacy.data?.session_slot_id) return;

  const { data: slot } = await supabase
    .from("session_slots")
    .select("*")
    .eq("id", legacy.data.session_slot_id)
    .single();

  if (!slot) return;

  const booked_count = Math.max(0, slot.booked_count - legacy.data.headcount);
  const status = booked_count < slot.max_slots ? "open" : slot.status;

  await supabase
    .from("session_slots")
    .update({ booked_count, status })
    .eq("id", legacy.data.session_slot_id);
}

export async function getBookingEmailContext(
  supabase: SupabaseClient,
  booking: {
    id: string;
    start_date: string | null;
    headcount: number;
    meals_requested?: boolean | null;
    carpool_requested?: boolean | null;
    room_requested?: boolean | null;
    room_decline_reason?: string | null;
    trip_duration_days?: 1 | 2 | null;
    session_slots?: { service_slug: string; date: string; price_cents: number } | null;
  }
) {
  const items = await fetchBookingItems(supabase, booking.id);

  if (items.length > 0) {
    const start = booking.start_date ?? items[0].start_date;
    const extras = extrasFromBookingRecord(booking);
    const sessionDurationDays = resolveSessionDurationDays(
      booking.trip_duration_days,
      items,
      extras
    );
    const participantCount = bookingGroupHeadcount(items);
    const coursesTotal = items.reduce(
      (sum, i) => sum + bookingItemLineTotalCents(i),
      0
    );

    return {
      summary: formatItemsSummary(
        items.map((i) => ({
          serviceSlug: i.service_slug,
          participantNames: i.participant_names?.length
            ? i.participant_names
            : undefined,
          quantity: i.quantity,
          durationDays: i.duration_days,
          startDate: i.start_date,
        }))
      ),
      date: start ? formatBookingDates(start, sessionDurationDays) : "",
      totalCents:
        coursesTotal +
        bookingExtrasTotalCents(extras, sessionDurationDays, participantCount, items),
      extrasSummary: formatBookingExtrasSummary(
        extras,
        sessionDurationDays,
        participantCount,
        items
      ),
      items,
    };
  }

  const slot = booking.session_slots;
  if (slot) {
    return {
      summary: formatItemsSummary([
        {
          serviceSlug: slot.service_slug,
          quantity: booking.headcount,
          durationDays: 1,
          startDate: slot.date,
        },
      ]),
      date: formatBookingDates(slot.date, 1),
      totalCents: slot.price_cents * booking.headcount,
      items: [],
    };
  }

  return {
    summary: "Booking",
    date: booking.start_date ?? "",
    totalCents: 0,
    items: [],
  };
}

export async function fetchBookingItems(
  supabase: SupabaseClient,
  bookingId: string
) {
  const { data } = await supabase
    .from("booking_items")
    .select("*")
    .eq("booking_id", bookingId)
    .order("created_at", { ascending: true });

  return data ?? [];
}
